name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build and release Electron app
      env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm run build
        npm run dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3  # Ensure this is v3
      with:
        name: dist
        path: dist

# Added a comment to force a fresh run